### ISSUE TITLE
NVML:Compilation error with clang compiler

### ISSUE THREAD

**Issue by skarana1** [intel/lkp-tests#46]
root@SSP-CLXAEP-CDI205/home/labuser/drill/lkp-tests # lkp run ./nvml-arch-none.yaml
2019-06-24 04:40:25 cd /lkp/benchmarks/nvml/src/test
2019-06-24 04:40:25 export CC=clang
2019-06-24 04:40:25 export CXX=clang++
2019-06-24 04:40:25 cd /lkp/benchmarks/nvml
2019-06-24 04:40:25 export CC=clang
2019-06-24 04:40:25 export CXX=clang++
2019-06-24 04:40:25 cp src/test/testconfig.sh.example src/test/testconfig.sh
2019-06-24 04:40:25 make EXTRA_CFLAGS=-DPAGE_SIZE=4096 -DUSE_VALGRIND USE_LLVM_LIBCPP=1 LIBCPP_INCDIR=/usr/local/libcxx/include/c++/v1/ LIBCPP_LIBDIR=/usr/local/libcxx/lib
make -C src all
make[1]: Entering directory '/lkp/benchmarks/nvml/src'
make -C libpmem
make[2]: Entering directory '/lkp/benchmarks/nvml/src/libpmem'
clang-8: error: unknown argument: '-ftree-loop-distribute-patterns'
clang-8: error: unknown argument: '-fno-semantic-interposition'
clang-8: warning: -Wl,-z: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: -Wl,now: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: -Wl,-z: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: -Wl,relro: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: -Wl,-sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
clang-8: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
../Makefile.inc:178: *** "clang -g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects  -fno-signed-zeros -fno-trapping-math  -fassociative-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake -std=gnu99 -fno-common -pthread -DSRCVERSION=\"1.6+git330.g57a94c062\" -DSDS_ENABLED -DNDCTL_GE_63 -DPAGE_SIZE=4096 -DUSE_VALGRIND  -dM -E -x c /dev/null -o /dev/null" failed.  Stop.
make[2]: Leaving directory '/lkp/benchmarks/nvml/src/libpmem'
make[1]: *** [Makefile:162: libpmem] Error 2
make[1]: Leaving directory '/lkp/benchmarks/nvml/src'
make: *** [Makefile:82: all] Error 2
build env failed
  /home/labuser/drill/lkp-tests/lib/debug.sh:12: die
  /home/labuser/drill/lkp-tests/tests/nvml:15: main
  :0:
root@SSP-CLXAEP-CDI205/home/labuser/drill/lkp-tests # uname -a
Linux SSP-CLXAEP-CDI205 5.1.12-785.native #1 SMP Wed Jun 19 07:09:10 UTC 2019 x86_64 GNU/Linux.
Workaround:-
By commenting out export CC=clang,export CXX=clang++( In the path  /lib/tests/nvml.sh ,in setup_compiler function),able to build successfully without errors.

**Comment by liuyd96** [comment]
Hi, skarana1.

The root cause is below error.
> clang-8: error: unknown argument: '-ftree-loop-distribute-patterns'
clang-8: error: unknown argument: '-fno-semantic-interposition'

On my local clear host, '-ftree-loop-distribute-patterns' and '-fno-semantic-interposition' are default.
It seems that Clang doesn't support the two arguments, unset the two arguments then lkp run could build nvml successfully.
> root@clear-lkp-30040~ # export | grep -w ftree
declare -x CFFLAGS="-g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize  -ftree-loop-vectorize  -Wl,-sort-common -Wl,--enable-new-dtags "
declare -x CFLAGS="-g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects  -fno-signed-zeros -fno-trapping-math  -fassociative-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake"
declare -x CXXFLAGS="-g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects  -fno-signed-zeros -fno-trapping-math  -fassociative-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake -fvisibility-inlines-hidden -Wl,--enable-new-dtags "
declare -x FFLAGS="-g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize  -ftree-loop-vectorize -Wl,--enable-new-dtags "
declare -x THEANO_FLAGS="floatX=float32,openmp=true,gcc.cxxflags=\"-ftree-vectorize -mavx\""

**Comment by skarana1** [comment]
Hi liuyd96,
Thank you so much for your prompt response.The root cause  which you suggested ,is that a workaround or fix?

**Comment by liuyd96** [comment]
Hi, skarana1

It should be a fix. LKP uses clang to build nvml but clang8 doesn't support '-ftree-loop-distribute-patterns' and '-fno-semantic-interposition'. 

So from lkp side, what we could do is removing the 2 arguments. (not sure whether other clang version support the 2 arguments.)

**Comment by liuyd96** [comment]
Hi, skarana1.

i have sent a small fix, please update your lcoal code after a while.

BTW, i'm confused that why clearlinux's env setting has set CFLAGS and CXXFLAGS as default.
The default setting will confuse the users who are using clang to do build.

my clear os.
> root@clear-lkp-30040~/lkp-tests # cat /etc/os-release 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=30040
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**Comment by skarana1** [comment]
Hi liuyd96,
Ya liuyd96, in code they are setting CFLAGS AND CXXFLAGS as default env variables.
Hence I commented out the CFLAGS AND C++FLAGS in the code(In the path /lib/tests/nvml.sh ,in setup_compiler function) and able to build packages successfully.

**Comment by skarana1** [comment]
Can you please provide me the patch for the above discussed issue?
Are you pushing the patch to the master?

**Comment by liuyd96** [comment]
`commit d9b71edc2d6a5e1bcfe965c247e9cedf4712b874
Author: Liu Yiding <yidingx.liu@intel.com>
Date:   Tue Aug 6 14:45:43 2019 +0800

    lib/tests/nvml.sh: fix clang error unknown arguments
    
    fix the following issue
    ------
    clang-8: error: unknown argument: '-ftree-loop-distribute-patterns'
    clang-8: error: unknown argument: '-fno-semantic-interposition'
    ------
    
    LKP uses clang to build nvml, sometimes local env has set default CFLAGS and CXXFLAGS,
    some options are not supported by clang.
    
    To avoid this issue, clear CFLAGS and CXXFLAGS.
    
    Signed-off-by: Liu Yiding <yidingx.liu@intel.com>
    Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/lib/tests/nvml.sh b/lib/tests/nvml.sh
index 799fbd3c..097fcbd7 100644
--- a/lib/tests/nvml.sh
+++ b/lib/tests/nvml.sh
@@ -42,6 +42,11 @@ build_env()
 
        # ./check_max_mmap.sh: line 44: /build/nvml/src/src/test/tools/anonymous_mmap/../../testconfig.sh: No such file or directory
        log_cmd cp src/test/testconfig.sh.example src/test/testconfig.sh
+       # clear CFLAGS and CXXFLAGS to avoid unknown arguments
+       # clang-8: error: unknown argument: '-ftree-loop-distribute-patterns'
+       # clang-8: error: unknown argument: '-fno-semantic-interposition'
+       CFLAGS=""
+       CXXFLAGS=""
        # All C++ container tests need customized version of libc --libc++ to compile. So specify the path of libc++ to make.
        log_cmd make EXTRA_CFLAGS="-DPAGE_SIZE=4096 -DUSE_VALGRIND" USE_LLVM_LIBCPP=1 LIBCPP_INCDIR=/usr/local/libcxx/include/c++/v1/ LIBCPP_LIBDIR=/usr/local/libcxx/lib || return
        log_cmd make EXTRA_CFLAGS="-DPAGE_SIZE=4096 -DUSE_VALGRIND" USE_LLVM_LIBCPP=1 LIBCPP_INCDIR=/usr/local/libcxx/include/c++/v1/ LIBCPP_LIBDIR=/usr/local/libcxx/lib test || return
`

**Comment by skarana1** [comment]
Can you share me the location of the patch ?

**Comment by liuyd96** [comment]
lib/tests/nvml.sh
