### ISSUE TITLE
ltp benchmark parameters

### ISSUE THREAD

**Issue by megha-an** [intel/lkp-tests#56]
Hi

I am running ltp benchmark through lkp (HiFive Unleashed (RISCV) yocto linux kernel 5.4.3 with 8GB RAM). Only 6GB is available when running LKP. I find  that lkp is expecting the ram size of the 8 GB to run the ltp.
Here is the error:

rm  due to not enough memory
need: 8192 MB, has: 6866 MB

And with HDD disk jobs 
This is the error:

rm  due to not enough HDD disks
need: 1, has: 0

Can we get more information on the test execution as we need to validate LTP through LKP framework on RISCV? 

Regards
Megha

**Comment by zhijianli88** [comment]
Hi Megha
 - For "no enough memory",  you can simply update the need_memory field to fit you OS
please note that some sub-tsts may consume a lots of memory.
```shell
~/lkp-tests$ git grep need_memory jobs/ltp*.yaml
jobs/ltp-1hdd-part1.yaml:need_memory: 3G
jobs/ltp-1hdd-part2.yaml:need_memory: 7G
jobs/ltp-1hdd-part2.yaml:need_memory: 4G
jobs/ltp-crashme-02.yaml:need_memory: 7G
jobs/ltp-physical-tbox.yaml:need_memory: 4G
jobs/ltp-stress.yaml:need_memory: 8G
jobs/ltp.yaml:need_memory: 3G
jobs/ltp.yaml:need_memory: 4G
```
- For "no enough HDD disks"
you have to install a hdd for this tests, because these tests may do some tests on this disk.
you can use 'lkp install --hdd /dev/xxx' to install a new disk to lkp framework
```shell
 ./bin/lkp install --help
Usage: lkp install [options] [<script>/<jobfile>]
options:
-f|--force: force to install testsuites
--hdd partition: HDD partition for IO tests
--ssd partition: SSD partition for IO tests
--dry-run: preview changes will made testbox by install
--china: install gem packages from the mirror in China
--skip-base: skip to install base support
--help: show this message
```

so kindly to let me know if you have any other questions.

**Comment by yangx-jy** [comment]
Hi @megha-an 

Do you have any other questions?
Please close the issue if you have no other questions.

Best Regards,
Xiao Yang
