### ISSUE TITLE
Perf compile fails due to missing files

### ISSUE THREAD

**Issue by Ankita-020696** [intel/lkp-tests#70]
I am porting lkp to Linux raspberrypi4-64 4.19.126-v8 #1 SMP PREEMPT Mon Jun 29 13:37:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux. 
When I use lkp install ./pft-50%-300s.yaml getting error as
**1**. **mv: cannot stat 'util/.session.o.tmp': No such file or directory
make[4]: *** [/home/root/lkp/lkp-tests/tmp-pkg/perf/src/linux/tools/build/Makefile.build:97: util/session.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/home/root/lkp/lkp-tests/tmp-pkg/perf/src/linux/tools/build/Makefile.build:139: util] Error 2
make[2]: *** [Makefile.perf:625: perf-in.o] Error 2
make[1]: *** [Makefile.perf:231: sub-make] Error 2
make: *** [Makefile:70: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...**
**Install perf-stat failed**
**2. mv: cannot stat './.builtin-script.o.tmp': No such file or directory
make[3]: *** [/home/root/lkp/lkp-tests/tmp-pkg/perf/src/linux/tools/build/Makefile.build:96: builtin-script.o] Error 1
make[3]: *** Waiting for unfinished jobs....**

Please refer attachment for the detailed log.
[log.txt](https://github.com/intel/lkp-tests/files/4911207/log.txt)

Thanks

**Comment by xiahui9527** [comment]
We don't test on the platform you mentioned since we mainly focus on the platform list in README. But it is great if you could port lkp-tests on other platform and we are happy to merge your pull request.
Just test pft on debian x86-64 which works fine. so it supposed to be build environment problem.
there is some error message in the log you post before the final break as below. maybe can fix it to see if any help.
The error happened when build perf which describe in pkg/perf/PKGBUILD. Try to build it manually to see if same error hit.
Any further information are welcome.  we are glad to help to run lkp-test on different distributions.

------
==> Entering fakeroot environment...
/home/root/lkp/lkp-tests/sbin/makepkg: line 199: fakeroot: command not found
Install mpstat failed
perf-profile: perf
==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges.
==> Making package: perf git-1 (Wed Jul  8 15:26:33 UTC 2020)
------

**Comment by xiahui9527** [comment]
@Ankita-020696 , any possible to install fakeroot in Linux raspberrypi4?

**Comment by Ankita-020696** [comment]
Yes I have installed fakeroot. The issue is with perf compilation.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by xiahui9527** [comment]
have you identified the root cause of perf compilation? let me know if anything we can help without Linux raspberrypi4 environment. Thanks.

**Comment by rli9** [comment]
Closed due to no update for 1 month.
